### ISSUE TITLE
Signing key renewal

### ISSUE THREAD

**Issue by marcoatpaladin** [aevoxyz/aevo-sdk#3]
Hey there,

Is the only way to renew signing keys through the UI?

Would like to set-and-forget my bot and not have to re-generate keys to post orders every week.

Can orders be posted simply with the api keys?

**Comment by alexchen314** [comment]
Order related endpoints require a signing key.

We have added a script to help with generating infinite expiry signing keys found here: https://github.com/aevoxyz/aevo-sdk/blob/master/generate_infinite_expiry_signing_key.py.

If you would prefer to have a long expiry as opposed to an infinite one, then you can edit the expiry parameter in the code as you wish.
